on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tags:
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Tarball
        run: tar -czvf kubeenv-${{ github.ref_name }}.tar.gz kubeenv
      - name: Create Release
        id: create_release
        uses: actions/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./kubeenv-${{ github.ref_name }}.tar.gz
          asset_name: kubeenv-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
